<%@ Page Title="Reject EWay Bill" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ConfirmRejectEwayBill.aspx.cs" Inherits="EWayBill_ConfirmRejectEwayBill" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <link href="../css/EwayCSSOne.css" rel="stylesheet" type="text/css">
    <link href="../css/EwayCSSTwo.css" rel="stylesheet" type="text/css">
    <link href="https://ewaybillgst.gov.in/css/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="https://ewaybillgst.gov.in/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://ewaybillgst.gov.in/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <%--<link href="https://ewaybillgst.gov.in/Styles/Login_Site.css" rel="stylesheet" type="text/css">  --%>
    <div style="text-align:center">
        <asp:Label ID="lblErrorMsg" runat="server"></asp:Label>
    </div>
    <div class="container-full">
        <div class="container-full " style="background-color: #F2F2F2;">
            <div class="pagelayout ">
                <table id="table_details" class="table_css table borderless " border="0">
                    <tbody>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold;">
                                <span style="margin-right: 5px">1.</span>E-WAY BILL Details</td>
                        </tr>
                        <tr style="height: 40px">
                            <td>
                                <span>eWay Bill No:</span>
                                <asp:Label ID="lblBillNoDetails" Style="font-size: 18px; font-weight: bold;" runat="server"></asp:Label>
                            </td>
                            <td>
                                <span>Generated Date:</span><asp:Label ID="lblGenDateDetails" Style="font-weight: bold;" runat="server"></asp:Label>
                            </td>
                            <td>
                                <span>Generated By:</span>
                                <asp:Label ID="lblGenDetails" Style="font-weight: bold;" runat="server"></asp:Label><span style="margin-right: 8px"></span>
                                <br />
                                <span>Valid Upto:</span>
                                <asp:Label ID="lblValidUPtoDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="height: 40px">
                            <td>
                                <span>Mode:</span>
                                <asp:Label ID="lblModeDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td>
                                <span>Approx Distance:</span>
                                <asp:Label ID="lblApxDistDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td></td>
                        </tr>
                        <tr style="height: 40px">
                            <td>

                                <span>Type:</span>
                                <asp:Label ID="lblTypeDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td colspan="2">
                                <span>Document Details:</span>
                                <asp:Label ID="lblDocDet" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">2.</span>Address Details</td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <table>
                                    <tbody>
                                        <tr>

                                            <td>
                                                <div class="bg-primary" style="width: 500px; height: 28px; padding: 5px; font-weight: bold">From </div>
                                                <textarea runat="server" id="txtGenBy" rows="2" cols="20" readonly="readonly" class=" form-control"
                                                    style="border-color: #4D4D4D; border-width: 1px; border-style: Solid; font-size: 11px; height: 130px;"></textarea>
                                            </td>
                                            <td style="width: 200px"></td>
                                            <td>
                                                <div class="bg-primary" style="width: 500px; height: 28px; padding: 5px; font-weight: bold"><span style="margin-right: 5px"></span>To</div>

                                                <textarea runat="server" id="txtSypplyTo" rows="2" cols="20" readonly="readonly" class=" form-control" style="border-color: #4D4D4D; border-width: 1px; border-style: Solid; font-size: 11px; height: 130px;"></textarea>
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">3.</span> Goods Details </td>
                        </tr>
                        <tr>
                            <td colspan="3">

                                <asp:GridView ID="GVItemList" runat="server" AutoGenerateColumns="false" Width="90%">
                                    <Columns>
                                        <asp:BoundField DataField="HSNCode" HeaderText="HSN Code" />
                                        <asp:BoundField DataField="productDesc" HeaderText="Product Descripition" />
                                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                                        <asp:BoundField DataField="taxableAmount" HeaderText="Taxable Amount Rs." />
                                        <asp:TemplateField HeaderText="Tax Rate (C+S+I+Cess)">
                                            <ItemTemplate>
                                                <asp:Label ID="lblCRate" runat="server" Text='<%#Eval("cgstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblSRate" runat="server" Text='<%#Eval("sgstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblIRate" runat="server" Text='<%#Eval("igstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblCessRate" runat="server" Text='<%#Eval("cessRate") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                </asp:GridView>
                            </td>
                        </tr>
                        <tr style="height: 35px; font-size: 13px">
                            <td colspan="3" class="form-inline">Total Tax'ble Amount <span class="classfont"></span>
                                <asp:Label ID="lblValue" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                                CGST Amount <span class="classfont"></span>
                                <asp:Label ID="lblcgst" runat="server" class="form-control1" Style="display: inline-block; width: 55px;"></asp:Label>
                                SGST Amount <span class="classfont"></span>
                                <asp:Label ID="lblsgst" runat="server" class="form-control1" Style="display: inline-block; width: 55px;"></asp:Label>
                                IGST Amount <span class="classfont"></span>
                                <asp:Label ID="lbligst" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                                CESS Amount <span class="classfont"></span>
                                <asp:Label ID="lblcess" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">4.</span>  Transportation Details</td>
                        </tr>
                        <tr style="height: 60px">
                            <td colspan="3">
                                <table class="table_css1">
                                    <tbody>
                                        <tr>
                                            <td style="vertical-align: top">
                                                <span>Transporter  ID &amp; Name   :</span><br />
                                                <asp:Label ID="lblTransportor" runat="server" Style="display: inline-block; font-weight: bold; width: 400px;"></asp:Label>
                                            </td>
                                            <td>

                                                <span>Transporter Doc. No &amp; Date   :</span><br />
                                                <asp:Label ID="lblTransDocNo" runat="server" Style="display: inline-block; font-weight: bold; width: 250px;"></asp:Label>
                                            </td>

                                            <td></td>

                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">5.</span>  Vehicle Details </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <asp:GridView ID="gvVehicleHistory" runat="server" class="table table-bordered"
                                    OnRowDataBound="gvVehicleHistory_RowDataBound" AutoGenerateColumns="false" Width="99%">
                                    <Columns>
                                        <asp:TemplateField HeaderText="Mode">
                                            <ItemTemplate>
                                                <asp:Label ID="lblMode" runat="server" Text='<%#Eval("TransMode") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:BoundField DataField="vehicleNo" HeaderText="Vehicle No" />
                                        <asp:BoundField DataField="transDocDate" HeaderText="Date" />
                                        <asp:BoundField DataField="transDocNo" HeaderText="Doc No" />
                                        <asp:BoundField DataField="FromPlace" HeaderText="From Place" />
                                        <asp:BoundField DataField="enteredDate" HeaderText="Entered Date" />
                                        <asp:BoundField DataField="userGSTINTransin" HeaderText="Entered By" />
                                        <asp:BoundField DataField="tripshtNo" HeaderText="Cons.EWB No." />
                                    </Columns>

                                </asp:GridView>
                            </td>
                        </tr>

                    </tbody>
                </table>

                <br>
            </div>

        </div>

    </div>

    <div style="text-align:center;">
        <asp:Button ID="btnRejectBill" runat="server" Text="Reject Eway Bill" OnClick="btnRejectBill_Click"
            OnClientClick="return confirm('Sure to Reject Eway Bill?');" />
        &nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btnExit" runat="server" Text="Exit" OnClick="btnExit_Click" />
    </div>

</asp:Content>


