<%@ Page Title="Extend Eway Bill Validity" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="ConfirmExtendEwayBill.aspx.cs" Inherits="EWayBill_ConfirmExtendEwayBill" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:ScriptManager runat="server" ID="ScriptManager1"></asp:ScriptManager>
    <link href="../css/EwayCSSOne.css" rel="stylesheet" type="text/css">
    <link href="../css/EwayCSSTwo.css" rel="stylesheet" type="text/css">
    <link href="../css/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="../css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="../css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <%--<link href="https://ewaybillgst.gov.in/Styles/Login_Site.css" rel="stylesheet" type="text/css">  --%>

    <script type="text/javascript">
        function validateAndConfirm(message) {
            var validated = Page_ClientValidate('ValRequired');
            if (validated) {
                return confirm(message);
            }
        }
    </script>
    <div style="text-align: center;">
        <asp:Label ID="lblErrorMsg" runat="server"></asp:Label>
    </div>
    <div class="container-full" style="margin-left: 10px;">

        <div class="container-full" style="background-color: #F2F2F2;">
            <div class="pagelayout">
                <table id="table_details" class="table_css table borderless " border="0">
                    <tbody>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold;">
                                <span style="margin-right: 5px">1.</span>E-WAY BILL Details</td>
                        </tr>
                        <tr style="height: 40px">
                            <td>
                                <span>eWay Bill No:</span>
                                <asp:Label ID="lblBillNoDetails" Style="font-size: 18px; font-weight: bold;" runat="server"></asp:Label>
                            </td>
                            <td>
                                <span>Generated Date:</span><asp:Label ID="lblGenDateDetails" Style="font-weight: bold;" runat="server"></asp:Label>
                            </td>
                            <td>
                                <span>Generated By:</span>
                                <asp:Label ID="lblGenDetails" Style="font-weight: bold;" runat="server"></asp:Label><span style="margin-right: 8px"></span>
                                <br />
                                <span>Valid Upto:</span>
                                <asp:Label ID="lblValidUPtoDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="height: 40px">
                            <td>

                                <span>Mode:</span>
                                <asp:Label ID="lblModeDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td>
                                <span>Approx Distance:</span>
                                <asp:Label ID="lblApxDistDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td></td>
                        </tr>
                        <tr style="height: 40px">
                            <td>

                                <span>Type:</span>
                                <asp:Label ID="lblTypeDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td colspan="2">
                                <span>Document Details:</span>
                                <asp:Label ID="lblDocDet" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">2.</span>Address Details</td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <table>
                                    <tbody>
                                        <tr>

                                            <td>
                                                <div class="bg-primary" style="width: 500px; height: 28px; padding: 5px; font-weight: bold">From </div>
                                                <textarea runat="server" id="txtGenBy" rows="2" cols="20" readonly="readonly" class=" form-control"
                                                    style="border-color: #4D4D4D; border-width: 1px; border-style: Solid; font-size: 11px; height: 130px;"></textarea>
                                            </td>
                                            <td style="width: 200px"></td>
                                            <td>
                                                <div class="bg-primary" style="width: 500px; height: 28px; padding: 5px; font-weight: bold"><span style="margin-right: 5px"></span>To</div>

                                                <textarea runat="server" id="txtSypplyTo" rows="2" cols="20" readonly="readonly" class=" form-control" style="border-color: #4D4D4D; border-width: 1px; border-style: Solid; font-size: 11px; height: 130px;"></textarea>
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">3.</span> Goods Details </td>
                        </tr>
                        <tr>
                            <td colspan="3">

                                <asp:GridView ID="GVItemList" runat="server" AutoGenerateColumns="false" Width="90%">
                                    <Columns>
                                        <asp:BoundField DataField="HSNCode" HeaderText="HSN Code" />
                                        <asp:BoundField DataField="productDesc" HeaderText="Product Descripition" />
                                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                                        <asp:BoundField DataField="taxableAmount" HeaderText="Taxable Amount Rs." />
                                        <asp:TemplateField HeaderText="Tax Rate (C+S+I+Cess)">
                                            <ItemTemplate>
                                                <asp:Label ID="lblCRate" runat="server" Text='<%#Eval("cgstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblSRate" runat="server" Text='<%#Eval("sgstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblIRate" runat="server" Text='<%#Eval("igstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblCessRate" runat="server" Text='<%#Eval("cessRate") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                </asp:GridView>
                            </td>
                        </tr>
                        <tr style="height: 35px; font-size: 13px">
                            <td colspan="3" class="form-inline">Total Tax'ble Amount <span class="classfont"></span>
                                <asp:Label ID="lblValue" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                                CGST Amount <span class="classfont"></span>
                                <asp:Label ID="lblcgst" runat="server" class="form-control1" Style="display: inline-block; width: 55px;"></asp:Label>
                                SGST Amount <span class="classfont"></span>
                                <asp:Label ID="lblsgst" runat="server" class="form-control1" Style="display: inline-block; width: 55px;"></asp:Label>
                                IGST Amount <span class="classfont"></span>
                                <asp:Label ID="lbligst" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                                CESS Amount <span class="classfont"></span>
                                <asp:Label ID="lblcess" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">4.</span>  Transportation Details</td>
                        </tr>
                        <tr style="height: 60px">
                            <td colspan="3">
                                <table class="table_css1">
                                    <tbody>
                                        <tr>
                                            <td style="vertical-align: top">
                                                <span>Transporter  ID &amp; Name   :</span><br />
                                                <asp:Label ID="lblTransportor" runat="server" Style="display: inline-block; font-weight: bold; width: 400px;"></asp:Label>
                                            </td>
                                            <td>

                                                <span>Transporter Doc. No &amp; Date   :</span><br />
                                                <asp:Label ID="lblTransDocNo" runat="server" Style="display: inline-block; font-weight: bold; width: 250px;"></asp:Label>
                                            </td>

                                            <td></td>

                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold">
                                <span style="margin-right: 5px">5.</span>  Vehicle Details </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <asp:GridView ID="gvVehicleHistory" runat="server" class="table table-bordered"
                                    OnRowDataBound="gvVehicleHistory_RowDataBound" AutoGenerateColumns="false" Width="99%">
                                    <Columns>
                                        <asp:TemplateField HeaderText="Mode">
                                            <ItemTemplate>
                                                <asp:Label ID="lblMode" runat="server" Text='<%#Eval("TransMode") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:BoundField DataField="vehicleNo" HeaderText="Vehicle No" />
                                        <asp:BoundField DataField="transDocDate" HeaderText="Date" />
                                        <asp:BoundField DataField="transDocNo" HeaderText="Doc No" />
                                        <asp:BoundField DataField="FromPlace" HeaderText="From Place" />
                                        <asp:BoundField DataField="enteredDate" HeaderText="Entered Date" />
                                        <asp:BoundField DataField="userGSTINTransin" HeaderText="Entered By" />
                                        <asp:BoundField DataField="tripshtNo" HeaderText="Cons.EWB No." />
                                    </Columns>

                                </asp:GridView>
                            </td>
                        </tr>

                        <tr id="tr_part_b" class="bg-primary">
                            <td colspan="2">Transportation Details (Part-B)
                            </td>
                        </tr>
                        <tr id="tr_part_transport">
                            <td colspan="2">
                                <table class="table text-left " clientidmode="Static" style="margin-bottom: 0; width: 500px; margin: 0 auto;">
                                    <tbody>
                                        <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">EWB Valid Till<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:Label ID="lblValidTillDate" runat="server"></asp:Label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Reason For Extension 
                                            </td>
                                            <td>
                                                <asp:DropDownList ID="ddExtendReason" runat="server">
                                                    <asp:ListItem Value="0" Text="-Select-"></asp:ListItem>
                                                    <asp:ListItem Value="1" Text="Natural Calamity"></asp:ListItem>
                                                    <asp:ListItem Value="2" Text="law &amp; Order"></asp:ListItem>
                                                    <asp:ListItem Value="4" Text="Transhipment"></asp:ListItem>
                                                    <asp:ListItem Value="5" Text="Accident"></asp:ListItem>
                                                    <asp:ListItem Value="99" Text="Others"></asp:ListItem>
                                                </asp:DropDownList>
                                                <asp:RequiredFieldValidator ID="rfvReason" runat="server" ControlToValidate="ddExtendReason" InitialValue="0"
                                                    Text="Required" ErrorMessage="Reason Requird" ValidationGroup="ValRequired"></asp:RequiredFieldValidator>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Remarks
                                            </td>
                                            <td>
                                                <asp:TextBox ID="txtExtendRemark" runat="server" MaxLength="50" Style="width: 200px"></asp:TextBox>
                                                <asp:RequiredFieldValidator ID="rfvRemark" runat="server" ControlToValidate="txtExtendRemark" InitialValue=""
                                                    Text="Required" ErrorMessage="Remark Requird" ValidationGroup="ValRequired"></asp:RequiredFieldValidator>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">From PIN Code<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:TextBox ID="txtFromPinCode" runat="server" MaxLength="6" Style="width: 80px"></asp:TextBox>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">From Place<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:TextBox ID="txtFromPlase" runat="server" MaxLength="100" Style="width: 200px"></asp:TextBox>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">Consignment Is<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:RadioButtonList ID="rblConsignmentType" runat="server" RepeatDirection="Horizontal">
                                                    <asp:ListItem Text="In Transit" Value="T"  Selected="True"></asp:ListItem>
                                                    <asp:ListItem Text="In Movement" Value="M" Selected="True"></asp:ListItem>
                                                </asp:RadioButtonList>
                                            </td>
                                        </tr>
                                         <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">From State<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:DropDownList ID="ddFromState" runat="server"></asp:DropDownList>
                                                <asp:RequiredFieldValidator ID="RFVState" runat="server" ControlToValidate="ddFromState"
                                                    Display="Dynamic" InitialValue="0" Text="Required" ErrorMessage="Required" ValidationGroup="ValRequired"></asp:RequiredFieldValidator>
                                            </td>
                                        </tr>
                                        <%--<tr>
                                            <td style="padding-right: 0px;" class="lbl_css">Address Line 1<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:TextBox ID="txtAddressLine1" runat="server" MaxLength="100" Style="width: 200px"></asp:TextBox>
                                            </td>
                                        </tr>
                                          <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">Address Line 2<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:TextBox ID="txtAddressLine2" runat="server" MaxLength="100" Style="width: 200px"></asp:TextBox>
                                            </td>
                                        </tr>--%>
                                         <%-- <tr>
                                            <td style="padding-right: 0px;" class="lbl_css">Address Line 3<span class="m-cir redcss"></span>
                                            </td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:TextBox ID="txtAddressLine3" runat="server" MaxLength="100" Style="width: 200px"></asp:TextBox>
                                            </td>
                                        </tr>--%>
                                        <tr>
                                            <td style="vertical-align: top;">Remaining Distance (in KM)<span class="m-cir redcss"></span>
                                            </td>
                                            <td class="form-inline">
                                                <asp:TextBox ID="txtDistance" runat="server" Style="width: 100px" MaxLength="4"></asp:TextBox>
                                                <asp:RequiredFieldValidator ID="RFVDistance" runat="server" ControlToValidate="txtDistance"
                                                    Display="Dynamic" InitialValue="" Text="Required" ErrorMessage="Required" ValidationGroup="ValRequired"></asp:RequiredFieldValidator>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding-right: 0px; vertical-align: top;" class="lbl_css">Mode<span class="m-cir redcss"></span></td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:RadioButtonList ID="rblMode" runat="server" CssClass="rdn_trans space" RepeatDirection="Horizontal" RepeatLayout="Table">
                                                    <asp:ListItem Value="5" Text="In Transit" Selected="True"></asp:ListItem>
                                                    <asp:ListItem Value="1" Text="Road" ></asp:ListItem>
                                                    <asp:ListItem Value="2" Text="Rail"></asp:ListItem>
                                                    <asp:ListItem Value="3" Text="Air"></asp:ListItem>
                                                    <asp:ListItem Value="4" Text="Ship"></asp:ListItem>
                                                    
                                                </asp:RadioButtonList>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding-right: 0px; vertical-align: top;" class="lbl_css">Vehicle Type</td>
                                            <td style="padding-right: 0px; vertical-align: top;">
                                                <asp:RadioButtonList ID="rblVehicleType" runat="server" CssClass="rdn_trans space" RepeatDirection="Horizontal" RepeatLayout="Table">
                                                    <asp:ListItem Value="R" Text="Regular" Selected="True"></asp:ListItem>
                                                    <asp:ListItem Value="O" Text="Over Dimensional Cargo"></asp:ListItem>
                                                </asp:RadioButtonList>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="form-inline">Vehicle No.<span class="m-cir redcss"></span></td>
                                            <td class="form-inline">
                                                <asp:TextBox ID="txtNewVehicleNo" runat="server" MaxLength="15"></asp:TextBox>
                                                <asp:RequiredFieldValidator ID="RFVVehicleNO" runat="server" ControlToValidate="txtNewVehicleNo"
                                                    Display="Dynamic" InitialValue="" Text="Required" ErrorMessage="Required" ValidationGroup="ValRequired"></asp:RequiredFieldValidator>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Transporter Doc. No.
                                            </td>
                                            <td>
                                                <asp:TextBox ID="txtTransDocNo" Style="width: 95px" MaxLength="15" runat="server"></asp:TextBox>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Transporter Date
                                            </td>
                                            <td>
                                                <asp:TextBox ID="txtTransDate" Style="width: 100px;" ReadOnly="true" runat="server"></asp:TextBox>
                                                <cc1:CalendarExtender ID="CalTransportDate" runat="server" EnableViewState="False" FirstDayOfWeek="Sunday"
                                                    Format="dd/MM/yyyy" TargetControlID="txtTransDate"></cc1:CalendarExtender>
                                                <asp:RequiredFieldValidator ID="RFVTransDate" runat="server" ControlToValidate="txtTransDate"
                                                    Display="Dynamic" InitialValue="" Text="Required" ErrorMessage="Required" ValidationGroup="ValRequired"></asp:RequiredFieldValidator>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr id="tr_part_vehicle">
                            <td colspan="2">
                                <table class="table" style="margin-bottom: 0; margin-top: 0;">
                                    <tbody>
                                        <tr>
                                            <td colspan="2">
                                                <div class="col-lg-12 text-center">
                                                    <asp:Button ID="btnExtendBillValidity" runat="server" Text="Extend Bill Validity" OnClick="btnExtendBillValidity_Click"
                                                        ValidationGroup="ValRequired" OnClientClick="return validateAndConfirm('Sure to Extend Bill Validity?');" />
                                                        &nbsp;&nbsp;&nbsp;&nbsp;
                                                    <asp:Button ID="btnExit" runat="server" Text="Exit" OnClick="btnExit_Click" />
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</asp:Content>



