<%@ Page Title="Pending Part B Update" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" 
    CodeFile="EWayPartBPending.aspx.cs" Inherits="EWayBill_EWayPartBPending" Culture="en-GB" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ScriptManager runat="server" ID="ScriptManager1" />
    <div>
        <asp:UpdateProgress ID="updProgress" AssociatedUpdatePanelID="pnlDetail" runat="server">
            <ProgressTemplate>
                <div style="position: absolute; visibility: visible; border: none; z-index: 100; width: 90%; height: 90%; background: #FAFAFA; filter: alpha(opacity=80); opacity: .8;">
                    <img alt="progress" src="../Images/progress-indicator.gif" style="position: relative; top: 40%; left: 40%;" />
                </div>
            </ProgressTemplate>
        </asp:UpdateProgress>
    </div>
    <asp:UpdatePanel ID="pnlDetail" runat="server">
      <ContentTemplate>
    <div align="center">
        <asp:Label ID="lblErrorMsg" runat="server" EnableViewState="false"></asp:Label>
    </div>
    <fieldset><legend>Show E-Way Bill By</legend>
    <table>
        <tbody>
            <tr>
                <td>
                </td>
                <td>
                    <asp:RadioButtonList ID="rbCategory" runat="server" RepeatDirection="Horizontal" AutoPostBack="true" OnSelectedIndexChanged="rbCategory_SelectedIndexChanged">
                        <asp:ListItem Value="EWBNO" Text="Bill No"></asp:ListItem>
                        <asp:ListItem Value="GENTR" Text="Generated by me (GSTIN)" ></asp:ListItem>
                        <asp:ListItem Value="GENDT" Text="Assigned For Transport (Date)" Selected="True" ></asp:ListItem>
                    </asp:RadioButtonList>
                </td>
            </tr>
            </tbody>
        </table>
        
    <br />
    <div>
    <div  style="float:left;">
    <asp:Panel ID="pnlBillNo" runat="server" Visible="false">
        <b>Bill Number </b> &nbsp;&nbsp;
        <asp:TextBox ID="txtBillNumber" runat="server" Width="100px" MaxLength="12" TextMode="Number"></asp:TextBox>
    </asp:Panel>
    <asp:Panel ID="pnlGenDate" runat="server" Visible="true">
        <b>Bill Date </b> &nbsp;&nbsp;
        <asp:TextBox ID="txtDate" runat="server" Width="100px"></asp:TextBox>
        <asp:Image ID="imgVehicleRecd" ImageAlign="Top" ImageUrl="../Images/btn_calendar.gif" runat="server" />&nbsp;&nbsp;
        <cc1:CalendarExtender ID="CalReceivedDate" runat="server" Enabled="True" EnableViewState="False"
            FirstDayOfWeek="Sunday" Format="dd/MM/yyyy" PopupButtonID="imgVehicleRecd" PopupPosition="BottomRight"
            TargetControlID="txtDate">
        </cc1:CalendarExtender>
    </asp:Panel>
    <asp:Panel ID="pnlGenGSTN" runat="server" Visible="false">
        <b>GSTIN </b> &nbsp;&nbsp;
        <asp:TextBox ID="txtGSTIN" runat="server" Width="100px"></asp:TextBox>
    </asp:Panel>
     
    </div>
    <div style="float:left;">
        <asp:DropDownList ID="ddTrasnporter" runat="server">
            <asp:ListItem Value="27AAACN1163G1ZR" Text="NAVBHARAT" Selected="True"></asp:ListItem>
            <asp:ListItem Value="27AAFFN5296A1ZA" Text="NAV JEEVAN AGENCY"></asp:ListItem>
            <asp:ListItem Value="27AAACB0466A1ZB" Text="BABAJI TRANSPORT"></asp:ListItem>
        </asp:DropDownList>   
        <asp:Button ID="btnShowBill" runat="server" Text="Show Eway Bill" OnClick="btnShowBill_Click" />
        &nbsp;&nbsp;
        <asp:Button ID="btnMultiVehicle" runat="server" Text="Multi Vehicle - Part B " OnClick="btnMultiVehicle_Click" />
    </div>
    </div>
            </fieldset>

    <fieldset> <legend>Bill Detail</legend>
    <asp:GridView ID="gvPendingPartB" runat="server" AutoGenerateColumns="false" CssClass="table"
        OnRowCommand="gvPendingPartB_RowCommand" AllowSorting="true" OnSorting="gvPendingPartB_Sorting">
        <Columns>
            <asp:TemplateField HeaderText="Sl">
                <ItemTemplate>
                    <%#Container.DataItemIndex + 1 %>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Eway Bill">
                <ItemTemplate>
                    <asp:LinkButton ID="lnkEwayNo" runat="server" Text='<%#Eval("ewbNo") %>' CommandArgument='<%#Eval("ewbNo") %>' CommandName="select"></asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="ewbDate" HeaderText="Bill Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="ewbDate" />
            <asp:BoundField DataField="genGstin" HeaderText="Generated By" SortExpression="genGstin" />
            <asp:BoundField DataField="docNo" HeaderText="Doc No" SortExpression="docNo" />
            <asp:BoundField DataField="docDate" HeaderText="Doc Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="docDate"/>
            <asp:BoundField DataField="delPlace" HeaderText="Delivery Place" SortExpression="delPlace" />
            <asp:BoundField DataField="delPinCode" HeaderText="Pin Code" SortExpression="delPinCode" />
            <asp:BoundField DataField="validUpto" HeaderText="Valid Upto" SortExpression="validUpto" />
            <asp:BoundField DataField="extendedTimes" HeaderText="Extended Times" SortExpression="extendedTimes" />
            <asp:BoundField DataField="status" HeaderText="Status" SortExpression="status" />
            <asp:BoundField DataField="rejectStatus" HeaderText="Reject Status" SortExpression="rejectStatus" />
        </Columns>
    </asp:GridView>
    </fieldset>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>

