<%@ Page Title="EWay Bill For Transport" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" 
    CodeFile="EWayGenByMe.aspx.cs" Inherits="EWayBill_EWayGenByMe" Culture="en-GB" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ScriptManager runat="server" ID="ScriptManager1" />
    <asp:Label ID="lblErrorMsg" runat="server" EnableViewState="false"></asp:Label>
    <fieldset><legend>Show E-Way Bill By</legend>
    <table>
        <tbody>
            <tr>
                <td>
                </td>
                <td>
                    <asp:RadioButtonList ID="rbCategory" runat="server" RepeatDirection="Horizontal" AutoPostBack="true" OnSelectedIndexChanged="rbCategory_SelectedIndexChanged">
                        <asp:ListItem Value="GENDT" Text="By Date" Selected="True"></asp:ListItem>
                        <asp:ListItem Value="GENTR" Text="By GSTIN" ></asp:ListItem>
                        <asp:ListItem Value="GENST" Text="By STATE" ></asp:ListItem>
                    </asp:RadioButtonList>
                </td>
            </tr>
        </tbody>
    </table>
    <br />    
    <div>
    <div style="float:left;">
    <asp:Panel ID="pnlBillNo" runat="server" Visible="false">
        <b>Bill Number </b> &nbsp;&nbsp;
        <asp:TextBox ID="txtBillNumber" runat="server" Width="100px" MaxLength="12"></asp:TextBox>
    </asp:Panel>
    <asp:Panel ID="pnlGenDate" runat="server" Visible="true">
        <b>Bill Date </b> &nbsp;&nbsp;
        <asp:TextBox ID="txtDate" runat="server" Width="80px"></asp:TextBox>
        <asp:Image ID="imgDate" ImageAlign="Top" ImageUrl="../Images/btn_calendar.gif" runat="server" />&nbsp;&nbsp;
        <cc1:CalendarExtender ID="CalExtDate" runat="server" Enabled="True" EnableViewState="False"
            FirstDayOfWeek="Sunday" Format="dd/MM/yyyy" PopupButtonID="imgDate" PopupPosition="BottomRight"
            TargetControlID="txtDate">
        </cc1:CalendarExtender>
    </asp:Panel>
    <asp:Panel ID="pnlGenGSTN" runat="server" Visible="false">
        <br />
        <b>GSTIN </b> &nbsp;&nbsp;
        <asp:TextBox ID="txtGSTIN" runat="server" Width="120px"></asp:TextBox>
        <asp:RegularExpressionValidator ID="RegExGSTIN" runat="server" ControlToValidate="txtGSTIN"
            ValidationExpression="^[0-9]{2}[a-zA-Z]{5}[0-9]{4}[a-zA-Z]{1}[1-9A-Za-z]{1}[Z]{1}[0-9a-zA-Z]{1}"
            Text="Please Enter Valid GSTIN" Display="Dynamic"></asp:RegularExpressionValidator>
    </asp:Panel>
    <asp:Panel ID="pnlGenState" runat="server" Visible="false">
        <br />
        <b>STATE </b> &nbsp;&nbsp;
        <asp:DropDownList ID="ddState" runat="server"></asp:DropDownList>
    </asp:Panel> 
    </div>
    <div style="float:left;">
        <asp:DropDownList ID="ddTrasnporter" runat="server">
            <asp:ListItem Value="27AAACN1163G1ZR" Text="NAVBHARAT CLEARING AGENTS PVT.LTD." Selected="True"></asp:ListItem>
            <asp:ListItem Value="27AAFFN5296A1ZA" Text="NAV JEEVAN AGENCY"></asp:ListItem>
            <%--<asp:ListItem Value="05AAACG0904A1ZL" Text="Testing"></asp:ListItem>--%>
        </asp:DropDownList>   
        <asp:Button ID="btnShowBill" runat="server" Text="Show Eway Bill" OnClick="btnShowBill_Click" />
    </div>
    </div>
    </fieldset>    
    <div>
        <asp:GridView ID="gvPendingPartB" runat="server" AutoGenerateColumns="false" CssClass="table"
            OnRowCommand="gvPendingPartB_RowCommand" AllowSorting="true" OnSorting="gvPendingPartB_Sorting">
            <Columns>
                <asp:TemplateField HeaderText="Sl">
                    <ItemTemplate>
                        <%#Container.DataItemIndex + 1 %>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Eway Bill">
                    <ItemTemplate>
                        <asp:LinkButton ID="lnkEwayNo" runat="server" Text='<%#Eval("ewbNo") %>' CommandArgument='<%#Eval("ewbNo") %>' CommandName="print"></asp:LinkButton>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="ewbDate" HeaderText="Bill Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="ewbDate" />
                <asp:BoundField DataField="genGstin" HeaderText="Generated By" SortExpression="genGstin" />
                <asp:BoundField DataField="docNo" HeaderText="Doc No" SortExpression="docNo" />
                <asp:BoundField DataField="docDate" HeaderText="Doc Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="docDate"/>
                <asp:BoundField DataField="delPlace" HeaderText="Delivery Place" SortExpression="delPlace" />
                <asp:BoundField DataField="delPinCode" HeaderText="Pin Code" SortExpression="delPinCode" />
                <asp:BoundField DataField="validUpto" HeaderText="Valid Upto" SortExpression="validUpto" />
                <asp:BoundField DataField="extendedTimes" HeaderText="Extended Times" SortExpression="extendedTimes" />
                <asp:BoundField DataField="status" HeaderText="Status" SortExpression="status" />
                <asp:BoundField DataField="rejectStatus" HeaderText="Reject Status" SortExpression="rejectStatus" />
            </Columns>
        </asp:GridView>
    </div>
</asp:Content>