<%@ Page Title="Generated By Other Party" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" 
    CodeFile="EWayOtherParty.aspx.cs" Inherits="EWayBill_EWayOtherParty" Culture="en-GB" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ScriptManager runat="server" ID="ScriptManager1" />    
    <asp:Label ID="lblErrorMsg" runat="server" EnableViewState="false"></asp:Label>
    <br />
    <fieldset><legend>Bill Generated By Other Party</legend>
        <span><b>Bill Date </b></span> <asp:TextBox ID="txtDate" runat="server" Width="100px"></asp:TextBox>
        <asp:Image ID="imgVehicleRecd" ImageAlign="Top" ImageUrl="../Images/btn_calendar.gif" runat="server" />&nbsp;&nbsp;
        <cc1:CalendarExtender ID="CalReceivedDate" runat="server" Enabled="True" EnableViewState="False"
            FirstDayOfWeek="Sunday" Format="dd/MM/yyyy" PopupButtonID="imgVehicleRecd" PopupPosition="BottomRight"
            TargetControlID="txtDate">
        </cc1:CalendarExtender>
         <asp:DropDownList ID="ddTrasnporter" runat="server">
            <asp:ListItem Value="27AAACN1163G1ZR" Text="NAVBHARAT CLEARING AGENTS" Selected="True"></asp:ListItem>
            <asp:ListItem Value="27AAFFN5296A1ZA" Text="NAV JEEVAN AGENCY"></asp:ListItem>
            <asp:ListItem Value="27AAACB0466A1ZB" Text="MAHARASHTRA"></asp:ListItem>
        </asp:DropDownList>   
        <asp:Button ID="btnShowBill" runat="server" Text="Show Eway Bill" OnClick="btnShowBill_Click" />
        &nbsp;&nbsp;&nbsp;
        <asp:LinkButton ID="lnkexport" runat="server" OnClick="lnkexport_Click">
        <asp:Image ID="mgExport" runat="server" ImageUrl="../images/Excel.jpg" ToolTip="Export To Excel" ImageAlign="AbsMiddle" />
        </asp:LinkButton>
        
        <div class="m clear"></div>
    
        <asp:GridView ID="gvPendingPartB" runat="server" AutoGenerateColumns="false" CssClass="table"
        OnRowCommand="gvPendingPartB_RowCommand" AllowSorting="true" OnSorting="gvPendingPartB_Sorting">
        <Columns>
            <asp:TemplateField HeaderText="Sl">
                <ItemTemplate>
                    <%#Container.DataItemIndex + 1 %>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Eway Bill">
                <ItemTemplate>
                    <asp:LinkButton ID="lnkEwayNo" runat="server" Text='<%#Eval("ewbNo") %>' CommandArgument='<%#Eval("ewbNo") %>' CommandName="select"></asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="ewbNo" HeaderText="Eway Bill" SortExpression="ewbNo" Visible="false" />
            <asp:BoundField DataField="ewayBillDate" HeaderText="Bill Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="ewbDate" />
            <asp:BoundField DataField="genGstin" HeaderText="Generated By" SortExpression="genGstin" />
            <asp:BoundField DataField="docNo" HeaderText="Doc No" SortExpression="docNo" />
            <asp:BoundField DataField="docDate" HeaderText="Doc Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="docDate"/>
            <asp:BoundField DataField="fromTradename" HeaderText="From Trader" SortExpression="fromTradename" />
            <asp:BoundField DataField="togstin" HeaderText="To GSTIN" SortExpression="togstin" />
            <asp:BoundField DataField="toTradename" HeaderText="To Trader" SortExpression="toTradename" />
            <asp:BoundField DataField="totInvValue" HeaderText="Total Value" SortExpression="totInvValue" />
            <asp:BoundField DataField="hsnCode" HeaderText="HSN" SortExpression="hsnCode" />
            <asp:BoundField DataField="hsnDesc" HeaderText="Desciption" SortExpression="hsnDesc" />
            <asp:BoundField DataField="status" HeaderText="Status" SortExpression="status" />
            <asp:BoundField DataField="rejectStatus" HeaderText="Reject Status" SortExpression="rejectStatus" />
            
        </Columns>
    </asp:GridView>
        
    </fieldset>
</asp:Content>



