using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using TaxProEWB.API;
using System.IO;
public partial class EWayBill_EWayOtherParty : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        Label lblTitle = (Label)Page.Master.FindControl("lblTitle");
        lblTitle.Text = "EWay Bill Generated By Other Party";

        if (!IsPostBack)
        {
            DBOperations.FillEWAYBillGSTIN2(ddTrasnporter, 0);
            Session["EWayRespObj"] = null;
            Session["EwayPrint"] = null;

            txtDate.Text = DateTime.Now.AddDays(-1).ToString("dd/MM/yyyy");
        }
    }
    private void GetEWayOtherParty()
    {
        string strAPI_GSTIN = ddTrasnporter.SelectedValue;
        EWBSession EwbSession = new EWBSession(strAPI_GSTIN);

        string strDate = DateTime.Now.ToString("dd/MM/yyyy");

        if (txtDate.Text.Trim() != "")
        {
            strDate = txtDate.Text.Trim();
        }

        TxnRespWithObj<List<EwayBillsofOtherParty>> TxnResp = EWBAPI.GetEWBOfOtherPartyAsync(EwbSession, strDate);
        
        if (TxnResp.IsSuccess)
        {
            string strEWayBillNo = "";
            Session["EWayRespObj"] = TxnResp.RespObj;
            gvPendingPartB.DataSource = TxnResp.RespObj;
            gvPendingPartB.DataBind();

            foreach (EwayBillsofOtherParty item in TxnResp.RespObj)
            {
                DateTime dtDocumentDate = DateTime.MinValue;

                string strBillGenDate = "", strDocumentNo = "";
                string strDeliveryPlace = "", strValidityDate = "", strStatusName = "";
                string strFromGSTIN = "", strToGSTIN = "", strUserGSTIN = "";
                char chRejectStatus = 'N';

                int PinCode = 0, StateCode = 0, ExtendedTimes = 0, lUser = 1;
                decimal decTotalInvoiceValue = 0;

                strEWayBillNo   = item.ewbNo.ToString();
                strBillGenDate  = item.ewayBillDate;
                strFromGSTIN    = item.fromgstin;
                strToGSTIN      = item.togstin;
                strUserGSTIN    = item.genGstin;
                strDocumentNo   = item.docNo;
                strStatusName   = item.status;
                chRejectStatus  = Convert.ToChar(item.rejectStatus);

                decTotalInvoiceValue = Convert.ToDecimal(item.totInvValue);

                string strDocDate = item.docDate;

                if (strDocDate != "" && strDocDate != null)
                {
                    if (item.docDate.Length > 10)
                    {
                        int index = item.docDate.IndexOf(' ');

                        strDocDate = item.docDate.Substring(0, index);
                    }
                    else
                    {
                        strDocDate = item.docDate.Substring(0, 10);
                    }

                    dtDocumentDate = DateTime.ParseExact(strDocDate, "M/d/yyyy", System.Globalization.CultureInfo.InvariantCulture);
                }


                int result = DBOperations.AddEWayBillConsole(strEWayBillNo, strBillGenDate, strUserGSTIN, strDocumentNo,
                 dtDocumentDate, strFromGSTIN, strToGSTIN, decTotalInvoiceValue, strDeliveryPlace, PinCode, StateCode,
                 strValidityDate, ExtendedTimes, strStatusName, chRejectStatus.ToString(), strAPI_GSTIN, lUser);
            }
        }
        else
        {
            Session["EWayRespObj"] = null;
            gvPendingPartB.DataSource = null;
            gvPendingPartB.DataBind();

            //lblErrorMsg.Text = "No Record Found For Selected Date & User - " + ddTrasnporter.SelectedItem.Text;

            lblErrorMsg.Text = TxnResp.TxnOutcome;
            lblErrorMsg.CssClass = "errorMsg";
        }
        //txtHeading.Text = "Get e-Way Bill assigned to you for transportation";
    }

    protected void gvPendingPartB_RowCommand(Object sender, GridViewCommandEventArgs e)
    {
        if (e.CommandName.ToLower() == "select")
        {
            string strBillNo = (string)e.CommandArgument;

            Session["EwayPrint"] = strBillNo;
            Session["userGSTIN"] = ddTrasnporter.SelectedValue;

            Response.Redirect("PrintEWayBill.aspx");
        }
    }

    protected void btnShowBill_Click(object sender, EventArgs e)
    {
        GetEWayOtherParty();
    }

    protected void gvPendingPartB_Sorting(object sender, GridViewSortEventArgs e)
    {

    }

    #region ExportData

    protected void lnkexport_Click(object sender, EventArgs e)
    {
        string strFileName = "EWayBill_" + DateTime.Now.ToString("dd/MM/yyyy hh:mm tt") + ".xls";

        ExportFunction("attachment;filename=" + strFileName, "application/vnd.ms-excel");

    }
    public override void VerifyRenderingInServerForm(Control control)
    {
        /*Verifies that the control is rendered */
    }
    private void ExportFunction(string header, string contentType)
    {
        if (Session["EWayRespObj"] != null)
        {

            Response.Clear();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", header);
            Response.Charset = "";
            this.EnableViewState = false;
            Response.ContentType = contentType;
            StringWriter sw = new StringWriter();
            HtmlTextWriter hw = new HtmlTextWriter(sw);
            gvPendingPartB.AllowPaging = false;
            gvPendingPartB.AllowSorting = false;

            gvPendingPartB.Columns[1].Visible = false;
            gvPendingPartB.Columns[2].Visible = true;

            // Retrive Resilt From Session 

        
            List<EwayBillsofOtherParty> RespObj = new List<EwayBillsofOtherParty>();
            RespObj = (List<EwayBillsofOtherParty>)Session["EWayRespObj"];

            gvPendingPartB.DataSource = RespObj;
            gvPendingPartB.DataBind();

            gvPendingPartB.RenderControl(hw);
            Response.Output.Write(sw.ToString());
            Response.End();
        }
                
    }
    #endregion
}