<%@ Page Title="Eway Bills By State" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" 
    CodeFile="EWayGenByState.aspx.cs" Inherits="EWayBill_EWayGenByState" EnableEventValidation="false" Culture="en-GB" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:ScriptManager runat="server" ID="ScriptManager1" />
    <div align="center">
        <asp:Label ID="lblErrorMsg" runat="server"></asp:Label>
    </div>
    <div class="clear"></div>
    <fieldset>
        <legend>EWay Bill By State</legend>
        <span><b>Bill Date </b></span> <asp:TextBox ID="txtDate" runat="server" Width="80px"></asp:TextBox>
        <asp:Image ID="imgVehicleRecd" ImageAlign="Top" ImageUrl="../Images/btn_calendar.gif" runat="server" />&nbsp;&nbsp;
        <cc1:CalendarExtender ID="CalBillDate" runat="server" Enabled="True" EnableViewState="False"
            FirstDayOfWeek="Sunday" Format="dd/MM/yyyy" PopupButtonID="imgVehicleRecd" PopupPosition="BottomRight"
            TargetControlID="txtDate" StartDate="01/01/2017">
        </cc1:CalendarExtender>        
        <asp:DropDownList ID="ddState" runat="server"></asp:DropDownList>
        <asp:DropDownList ID="ddTrasnporter" runat="server">
            <asp:ListItem Value="27AAACN1163G1ZR" Text="NAVBHARAT" Selected="True"></asp:ListItem>
            <asp:ListItem Value="27AAFFN5296A1ZA" Text="NAV JEEVAN AGENCY"></asp:ListItem>
            <asp:ListItem Value="27AAACB0466A1ZB" Text="BABAJI TRANSPORT"></asp:ListItem>
        </asp:DropDownList>   
        &nbsp;<asp:Button ID="btnShowBill" runat="server" Text="Show Eway Bill" OnClick="btnShowBill_Click" />
        &nbsp;&nbsp;&nbsp;&nbsp;
        <asp:LinkButton ID="lnkexport" runat="server" OnClick="lnkexport_Click">
        <asp:Image ID="mgExport" runat="server" ImageUrl="../images/Excel.jpg" ToolTip="Export To Excel" ImageAlign="AbsMiddle" />
        </asp:LinkButton>
        <div class="m clear"></div>
        <div>
            <asp:GridView ID="gvEWayBill" runat="server" AutoGenerateColumns="false" CssClass="table"
                OnRowCommand="gvEWayBill_RowCommand" AllowSorting="true" OnSorting="gvEWayBill_Sorting">
                <Columns>
                    <asp:TemplateField HeaderText="Sl">
                        <ItemTemplate>
                            <%#Container.DataItemIndex + 1 %>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Eway Bill">
                        <ItemTemplate>
                            <asp:LinkButton ID="lnkEwayNo" runat="server" Text='<%#Eval("ewbNo") %>' CommandArgument='<%#Eval("ewbNo") %>' CommandName="print"></asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="ewbNo" HeaderText="Eway Bill" SortExpression="ewbNo" Visible="false" />
                    <asp:BoundField DataField="ewbDate" HeaderText="Bill Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="ewbDate" />
                    <asp:BoundField DataField="genGstin" HeaderText="Generated By" SortExpression="genGstin" />
                    <asp:BoundField DataField="docNo" HeaderText="Doc No" SortExpression="docNo" />
                    <asp:BoundField DataField="docDate" HeaderText="Doc Date" DataFormatString="{0:dd/MM/yyyy hh:mm tt}" SortExpression="docDate"/>
                    <asp:BoundField DataField="delPlace" HeaderText="Delivery Place" SortExpression="delPlace" />
                    <asp:BoundField DataField="delPinCode" HeaderText="Pin Code" SortExpression="delPinCode" />
                    <asp:BoundField DataField="validUpto" HeaderText="Valid Upto" SortExpression="validUpto" />
                    <asp:BoundField DataField="extendedTimes" HeaderText="Extended Times" SortExpression="extendedTimes" />
                    <asp:BoundField DataField="status" HeaderText="Status" SortExpression="status" />
                    <asp:BoundField DataField="rejectStatus" HeaderText="Reject Status" SortExpression="rejectStatus" />
                </Columns>
            </asp:GridView>
        </div>
    </fieldset>
</asp:Content>