<%@ Page Title="Update Part B" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" 
    CodeFile="UpdatePartB.aspx.cs" Inherits="EWayBill_UpdatePartB" Culture="en-GB" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:ScriptManager runat="server" ID="ScriptManager1"></asp:ScriptManager>
    <link href="../css/EwayCSSOne.css" rel="stylesheet" type="text/css">
    <link href="../css/EwayCSSTwo.css" rel="stylesheet" type="text/css">
    <link href="../css/jquery-ui.css" rel="stylesheet" type="text/css">
    <link href="../css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="../css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <%--<link href="https://ewaybillgst.gov.in/Styles/Login_Site.css" rel="stylesheet" type="text/css">  --%>

    <script type="text/javascript">
        function validateAndConfirm(message) {
            var validated = Page_ClientValidate('Required1');
            if (validated) {
                return confirm(message);
            }
        }
    </script>

    <asp:Label ID="lblErrorMsg" runat="server"></asp:Label>

    <div class="container-full">

        <div class="container-full " style="background-color: #F2F2F2;">

            <div class="pagelayout ">
                <table id="table_details" class="table_css table borderless " border="0">
                    <tbody>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold;"><span style="margin-right: 5px">1.</span>E-WAY BILL Details</td>
                        </tr>
                        <tr style="height: 40px">
                            <td>
                                <span>eWay Bill No:</span>
                                <asp:Label ID="lblBillNoDetails" Style="font-size: 18px; font-weight: bold;" runat="server"></asp:Label>
                            </td>
                            <td>
                                <span>Generated Date:</span><asp:Label ID="lblGenDateDetails" Style="font-weight: bold;" runat="server"></asp:Label>
                            </td>
                            <td>
                                <span>Generated By:</span>
                                <asp:Label ID="lblGenDetails" Style="font-weight: bold;" runat="server"></asp:Label><span style="margin-right: 8px"></span>
                                <br>
                                <span>Valid Upto:</span>
                                <asp:Label ID="lblValidUPtoDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="height: 40px">
                            <td>

                                <span>Mode:</span>

                                <asp:Label ID="lblModeDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td>
                                <span>Approx Distance:</span>
                                <asp:Label ID="lblApxDistDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td></td>
                        </tr>
                        <tr style="height: 40px">
                            <td>

                                <span>Type:</span>
                                <asp:Label ID="lblTypeDetails" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                            <td colspan="2">
                                <span>Document Details:</span>
                                <asp:Label ID="lblDocDet" runat="server" Style="font-weight: bold;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold"><span style="margin-right: 5px">2.</span>Address Details</td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <table>
                                    <tbody>
                                        <tr>

                                            <td>
                                                <div class="bg-primary" style="width: 500px; height: 28px; padding: 5px; font-weight: bold">From </div>


                                                <textarea runat="server" id="txtGenBy" rows="2" cols="20" readonly="readonly" class=" form-control" style="border-color: #4D4D4D; border-width: 1px; border-style: Solid; font-size: 11px; height: 130px;">
</textarea>
                                            </td>
                                            <td style="width: 200px"></td>
                                            <td>
                                                <div class="bg-primary" style="width: 500px; height: 28px; padding: 5px; font-weight: bold"><span style="margin-right: 5px"></span>To</div>

                                                <textarea runat="server" id="txtSypplyTo" rows="2" cols="20" readonly="readonly" class=" form-control" style="border-color: #4D4D4D; border-width: 1px; border-style: Solid; font-size: 11px; height: 130px;"></textarea>
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold"><span style="margin-right: 5px">3.</span> Goods Details </td>
                        </tr>
                        <tr>
                            <td colspan="3">

                                <asp:GridView ID="GVItemList" runat="server" AutoGenerateColumns="false" Width="98%">
                                    <Columns>
                                        <asp:BoundField DataField="HSNCode" HeaderText="HSN Code" />
                                        <asp:BoundField DataField="productDesc" HeaderText="Product Descripition" />
                                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                                        <asp:BoundField DataField="taxableAmount" HeaderText="Taxable Amount Rs." />
                                        <asp:TemplateField HeaderText="Tax Rate (C+S+I+Cess)">
                                            <ItemTemplate>
                                                <asp:Label ID="lblCRate" runat="server" Text='<%#Eval("cgstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblSRate" runat="server" Text='<%#Eval("sgstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblIRate" runat="server" Text='<%#Eval("igstRate") %>'></asp:Label>
                                                +
                            <asp:Label ID="lblCessRate" runat="server" Text='<%#Eval("cessRate") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                </asp:GridView>
                            </td>
                        </tr>
                        <tr style="height: 35px; font-size: 13px">
                            <td colspan="3" class="form-inline">Total Tax'ble Amount <span class="classfont"></span>
                                <asp:Label ID="lblValue" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                                CGST Amount <span class="classfont"></span>
                                <asp:Label ID="lblcgst" runat="server" class="form-control1" Style="display: inline-block; width: 55px;"></asp:Label>
                                SGST Amount <span class="classfont"></span>
                                <asp:Label ID="lblsgst" runat="server" class="form-control1" Style="display: inline-block; width: 55px;"></asp:Label>
                                IGST Amount <span class="classfont"></span>
                                <asp:Label ID="lbligst" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                                CESS Amount <span class="classfont"></span>
                                <asp:Label ID="lblcess" runat="server" class="form-control1" Style="display: inline-block; width: 120px;"></asp:Label>
                            </td>
                        </tr>
                        <tr style="border-top: 2px solid Gray">
                            <td class="bg-primary" colspan="3" style="height: 30px; font-weight: bold"><span style="margin-right: 5px">4.</span>  Transportation Details</td>
                        </tr>
                        <tr style="height: 40px">
                            <td colspan="3">
                                <table class="table_css1">
                                    <tbody>
                                        <tr>
                                            <td style="vertical-align: top">
                                                <span>Transporter  ID &amp; Name   :</span>
                                                <asp:Label ID="lblTransportor" runat="server" Style="display: inline-block; font-weight: bold; width: 400px;"></asp:Label>
                                            </td>

                                            <td>

                                                <span>Transporter Doc. No &amp; Date   :</span>
                                                <asp:Label ID="lblTransDocNo" runat="server" Style="display: inline-block; font-weight: bold; width: 250px;"></asp:Label>
                                            </td>

                                            <td></td>

                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
                <div id="pnl_upd_actual">
                    <div id="actDiv2" style="text-align: center; width: 630px;">
                        <center>
                            <table class="HeadTable table table-bordered table-hover table-responsive" id="HeadTable">
                                <tbody>
                                    <tr>
                                        <td colspan="2" class="table table-bordered " align="center">
                                            <span id="eway_text" style="color: #CC0000; font-weight: bold;"> Vehicle Updation For The EWB No:</span>
                                            <asp:Label ID="lblEWayNo" runat="server" style="color: #CC0000; font-weight: bold;"></asp:Label>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <table id="tbl_part_b" class="table table-bordered table-hover table-responsive" style="margin-bottom: 0; width: 100%;">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="2" class="table table-bordered " style="background-color: steelblue;"><span id="ctl00_ContentPlaceHolder1_Label3" style="color: White; font-weight: bold;">Update Part-B</span></td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="Label2" style="font-weight: bold;">Mode Of Transport</span>
                                                        </td>
                                                        <td>
                                                            <asp:RadioButtonList ID="rblMode" runat="server" CssClass="rdn_trans space" RepeatDirection="Horizontal" RepeatLayout="Table">
                                                                <asp:ListItem Value="1" Text="Road" Selected="True"></asp:ListItem>
                                                                <asp:ListItem Value="2" Text="Rail"></asp:ListItem>
                                                                <asp:ListItem Value="3" Text="Air"></asp:ListItem>
                                                                <asp:ListItem Value="4" Text="Ship"></asp:ListItem>
                                                            </asp:RadioButtonList>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="lbl_vehNo" style="font-weight: bold;">Vehicle No</span><span style="color: red;">*</span>
                                                        </td>
                                                        <td>
                                                            <asp:TextBox ID="txtVehicleNo" runat="server" placeholder="Vehicle No" Width="120px" MaxLength="15" style="text-transform: uppercase"></asp:TextBox>
                                                            <asp:RequiredFieldValidator ID="RFVVehicleNo" runat="server" ControlToValidate="txtVehicleNo" SetFocusOnError="true"
                                                                Display="Dynamic" InitialValue="" Text="Required" ErrorMessage="Required" ValidationGroup="Required1"></asp:RequiredFieldValidator>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="lbl_vehType" style="font-weight: bold;">Vehicle Type</span><span style="color: red;">*</span>
                                                        </td>
                                                        <td>
                                                            <asp:RadioButtonList ID="rblVehicleType" runat="server" CssClass="rdn_trans space" RepeatDirection="Horizontal" RepeatLayout="Table">
                                                                <asp:ListItem Value="R" Text="Regular" Selected="True"></asp:ListItem>
                                                                <asp:ListItem Value="O" Text="Over Dimensional Cargo"></asp:ListItem>
                                                            </asp:RadioButtonList>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="lblPlace" style="font-weight: bold;">Place of Change</span><span style="color: red;">*</span>
                                                        </td>
                                                        <td>
                                                            <asp:TextBox ID="txtFromPlace" runat="server" placeholder="From Place" MaxLength="49"></asp:TextBox>
                                                            <asp:RequiredFieldValidator ID="RFVPlace" runat="server" ControlToValidate="txtFromPlace" SetFocusOnError="true"
                                                                Display="Dynamic" InitialValue="" Text="Required" ErrorMessage="Required" ValidationGroup="Required1"></asp:RequiredFieldValidator>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="lblFromState" style="font-weight: bold;">From State</span><span style="color: red;">*</span>
                                                        </td>
                                                        <td>
                                                            <asp:DropDownList ID="ddState" runat="server"></asp:DropDownList>
                                                            <asp:RequiredFieldValidator ID="rfvState" runat="server" ControlToValidate="ddState"
                                                                Display="Dynamic" InitialValue="0" Text="Required" ErrorMessage="Required" ValidationGroup="Required1"></asp:RequiredFieldValidator>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="lbl_rsn" style="font-weight: bold;">Reason</span><span style="color: red;">*</span>
                                                        </td>
                                                        <td>
                                                            <asp:DropDownList ID="ddReason" runat="server">
                                                                <asp:ListItem Value="0" Text="--Select Reason--"></asp:ListItem>
                                                                <asp:ListItem Value="1" Text="To Break Down"></asp:ListItem>
                                                                <asp:ListItem Value="2" Text="Due To Transhipment"></asp:ListItem>
                                                                <asp:ListItem Value="3" Text="Others"></asp:ListItem>
                                                                <asp:ListItem Value="4" Text="First Time" Selected="True"></asp:ListItem>
                                                            </asp:DropDownList>
                                                            <asp:RequiredFieldValidator ID="rfvReason" runat="server" ControlToValidate="ddReason"
                                                                Display="Dynamic" InitialValue="0" Text="Required" ErrorMessage="Required" ValidationGroup="Required1"></asp:RequiredFieldValidator>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>
                                                            <span id="lblTranDocNo" class="lblTranDocNo" style="display: inline-block; font-weight: bold; width: 178px;">Transporter Doc. No. &amp; Date</span>
                                                        </td>
                                                        <td>
                                                            <asp:TextBox ID="txtTransDocNo" placeholder="Doc No/LR No" runat="server" MaxLength="15" Width="100px"></asp:TextBox>
                                                                & Date
                                                            <asp:TextBox ID="txtVehicleDate" runat="server" Width="100px" placeholder="Dispatch Date"></asp:TextBox>
                                                            <cc1:CalendarExtender ID="CalTransportDate" runat="server" EnableViewState="False" FirstDayOfWeek="Sunday"
                                                                Format="dd/MM/yyyy" TargetControlID="txtVehicleDate"></cc1:CalendarExtender>
                                                            <span id="lblDateFormate" style="color: Red; font-size: X-Small; font-weight: bold; display: none;">Enter in dd/mm/yyyy format</span>
                                                            <asp:RequiredFieldValidator ID="RFVDispatchDate" runat="server" InitialValue="" ControlToValidate="txtVehicleDate"
                                                                Display="Dynamic" ErrorMessage="*" Text="Required" ValidationGroup="Required1" SetFocusOnError="true"></asp:RequiredFieldValidator>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center" colspan="2">
                                                            <asp:Button ID="btnSubmit" Text="Upadate Part B" runat="server" OnClick="btnSubmit_Click" ValidationGroup="Required1" 
                                                                OnClientClick="return validateAndConfirm('Sure to Update Part B?');"/>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </center>
                    </div>
                    
                </div>
                <br>
                <div id="dr_veh" style="text-align: center; width: 80%;">
                    <center>
                        <span id="lbl_caption" style="color: #CC0000; font-weight: bold;">**** Vehicle Updation History ****</span>
                    </center>
                    <asp:GridView ID="gvVehicleHistory" runat="server" class="table table-bordered" 
                                   OnRowDataBound="gvVehicleHistory_RowDataBound" AutoGenerateColumns="false" Width="99%">
                        <Columns>
                            <asp:TemplateField HeaderText="Mode">
                                <ItemTemplate>
                                    <asp:Label ID="lblMode" runat="server" Text='<%#Eval("TransMode") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:BoundField DataField="vehicleNo" HeaderText="Vehicle No" />
                            <asp:BoundField DataField="transDocDate" HeaderText="Date" />
                            <asp:BoundField DataField="transDocNo" HeaderText="Trans Doc No" />
                            <asp:BoundField DataField="FromPlace" HeaderText="From Place" />
                            <asp:BoundField DataField="userGSTINTransin" HeaderText="Updated By" />
                            <asp:BoundField DataField="enteredDate" HeaderText="Entered Date" />
                            <asp:BoundField DataField="tripshtNo" HeaderText="Cons.EWB No." />
                        </Columns>

                    </asp:GridView>
                </div>
            </div>

        </div>

    </div>

</asp:Content>

